version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'
    labels:
      - dependencies
      - dependabot
      - web-team
    reviewers:
      - 'KTH/web-team'
    ignore:
      - dependency-name: 'eslint'
        versions: ['9.x']
      - dependency-name: 'mongoose'
        versions: ['8.x']
