services:
  db:
    image: mongo:latest
    ports:
      - 27017
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', '''db.runCommand("ping").ok''', 'localhost:27017/test']
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    image: $LOCAL_IMAGE_ID
    environment:
      SERVICE_PUBLISH: '/api/node'
      SERVER_PORT: 3001
      API_KEYS_0: '?name=devClient&apiKey=1234&scope=write&scope=read'
      MONGODB_URI: 'mongodb://db'
    healthcheck:
      test: ['CMD', 'curl', 'http://app:3001/api/node/_monitor']
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 3001
    depends_on:
      db:
        condition: service_healthy

  integration-tests:
    build: ./test/integration
    environment:
      INTEGRATION_TEST_BASEURL: 'http://app:3001/api/node'
      INTEGRATION_TEST_SUCCESS_DELAY: '${SUCCESS_DELAY:-0}'
      INTEGRATION_TEST_FAILURE_DELAY: '${FAILURE_DELAY:-0}'
    depends_on:
      app:
        condition: service_healthy
