trigger: none
pr:
  - main

variables:
  - group: team-webb-general-params
  - name: imageName
    value: node-api
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/Dockerfile'
  - name: tag
    value: '$(Build.SourceVersion)'

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: unit_test
    steps:
      - template: templates/test/npm-test.yml@cet-iac
        parameters:
          nodeVersion: 18

  - job: integration_test
    steps:
      - template: templates/test/docker-test.yml@cet-iac
        parameters:
          dockerComposeFilePaths:
            - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'
          dockerfilePath: $(dockerfilePath)
          imageName: $(imageName)
          tag: $(tag)
